---
title: "GoldenRuleMonth"
output: html_notebook
---


```{r}
library(quantmod)
start <- as.Date("2008-01-01")
end <- as.Date("2018-01-01")

getSymbols("AAPL", src = "yahoo", from = start, to = end)
```

In the golden rule approach, we have to learn from prices firstly
```{r}
n <- exp(1)^(-1)

learning <- function(learn_sequence){
  maximum <- -Inf
  for (i in learn_sequence){
    if (i > maximum){maximum <- i}
  }
  return(i)
}
```

Than we use golden rule algorithm
```{r}
golden_rule <- function(numbers){
  rangs <- sort(numbers, decreasing = TRUE)
  test_quantity <- round(length(numbers)*n)
  maximum <- learning(numbers[1:test_quantity])
  last_n <- 0
  for (i in numbers[test_quantity + 1:length(numbers)-1]){
    if (!is.na(i)){
    last_n <- i
    if (i > maximum){return(c(i, which(rangs == i)))}
  }}
  return(c(last_n, which(rangs == last_n)))
}
```

Rebuilding the data
```{r}
monthdatas<-new.env()

c <- 0
for (i in 2008:2017){
  for (j in 1:12){
    if (j >= 10){
      m <- paste(toString(i),"-",toString(j), sep="")
    }
    else{
      m <- paste(toString(i),"-0",toString(j), sep="")
    }
    month_data <- data <- AAPL[m, "AAPL.Open"]
    monthdatas[[toString(c)]] <- coredata(month_data)
    c = c +1
  }
}
```


Experimental testing of golden rule on Apple stock prices:
```{r}
golden <- c()
optimal <- c()
month <- c()
maximum <- c()
pricespread <- c()
rangs <- c()

counter <- 0
for (i in 1:length(monthdatas)-1){
    counter <- counter + 1
    crdata <- monthdatas[[toString(i)]]
    obtained.data <- golden_rule(crdata)
    golden[counter] <- obtained.data[1]
    rangs[counter] <- obtained.data[2]
    optimal[counter] <- min(crdata)
    maximum[counter] <- max(crdata)
    pricespread[counter] <- max(crdata) - min(crdata)
    month[counter] <- i
}


difference <- c(maximum - golden)
normdifferece <- c(difference / pricespread)

x <- c(golden/maximum)

df <- data.frame(month, golden, optimal, maximum, difference, pricespread, normdifferece, x)
```

Drawing the histogram of ranks
```{r}
hist(rangs, prob=TRUE,col="black",border="white", main="Expected maximum rangs distribution", xlab = "rangs")
box(bty="l")
lines(density(rangs,na.rm=T),col="red",lwd=3)
grid(nx=NA,ny=NULL,lty=1,lwd=1,col="gray")
```
```{r}
mean(rangs)
```


```{r}
plot(df$golden, xlab="Time Periods", ylab="Stock  Prices")
lines(df$optimal, col="green")
lines(df$maximum, col="red")

```



